"""change_duration_minutes_to_question_count

Revision ID: 6f6a492cb401
Revises: 5a9b2f305a1b
Create Date: 2025-09-19 11:07:14.222157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6a492cb401'
down_revision = '5a9b2f305a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_count', sa.Integer(), nullable=True))
        batch_op.drop_column('duration_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('question_count')

    # ### end Alembic commands ###
